name: Bomb
version: 1.0
main: bomb.Main

commands:
  bomb:
    usage: /<command> [type] [target] [power]
    aliases: [bb]
  timebomb:
    usage: /<command> [target] [time] [power] [text]
    aliases: [tb]
  getbomb:
    usage: /<command> [target] [type] [count]
    aliases: [gb]